import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Card from "./Components/card/Card";
import { useState, useEffect } from "react";

export default function Home() {
  const [products, setProducts] = useState([]);
  const [textInput, setTextInput] = useState("");
  const [filteredProducts, setfilteredProducts] = useState([]);

  const fetchData = () => {
    fetch(`https://api.escuelajs.co/api/v1/products`)
      .then((res) => res.json())
      .then((data) => {
        setProducts(data);
        setfilteredProducts(data);
      });
  };

  useEffect(fetchData, []);

  const handleChange = (e) => {
    setTextInput(e.target.value);
  };

  useEffect(() => {
    if (textInput) {
      const filtered = filteredProducts.filter((product) => {
        return product.title.toLowerCase().includes(textInput.toLowerCase());
      });
      setfilteredProducts(filtered);
    } else {
      setfilteredProducts(products);
    }
  }, [textInput]);

  console.log(filteredProducts);

  return (
    <>
      <Head>
        <title>JAM Shopper</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="./favicon.ico" />
      </Head>
      <main className="main-container">
        <div>
          <div className={styles.herocontainer}>
            <h1>Grocify</h1>
            <input
              className={styles.searchbar}
              type="text"
              placeholder="Search product"
              onChange={handleChange}
            />
          </div>
          <div className={styles.grid}>
            {filteredProducts.map((product) => (
              <Card
                key={product.id}
                name={product.title}
                description={product.description}
                image={product.images[0]} // assuming the first image is the main one
              />
            ))}
          </div>
        </div>
      </main>
    </>
  );
}
